server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: onanamboussistael@gmail.com
    password: "jhth pdvb oxjk jrld"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

app:
  jwt:
    secret: ${JWT_SECRET:MaCleSecretePourLeDevLocalEtProduction123456789SuperLongue32Chars!}
    expiration: 86400000
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4300}

upload:
  dir: uploads
  server:
    error:
      include-message: always
      include-binding-errors: always

  logging:
    level:
      root: DEBUG

notch pay:
        public-key: pk_test.oFmW9V8vJJkoDdD7F254dvToR16ObV9L88TRSWD5MqIKmdAdzC6zlhXO8Owmylb2ionb6Kgo637XofOmotU2rIt7CnDeowjTg8Q4X6uVeffqS3whYToJ9S35LrlOP
        secret-key: sk_test.bZjcBCTD2VcNdjdWRgeCvBTG8XxQD6WlyYIEbtpAvptvub6N495s4cC5BzaOYivKfye3mXHU0JSITg5LeuiTPG8pilb3y89YO5TOHB78h88a3MTYDwTSLzOVqdWfA